<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Cadastro</title>

    <style>
	
		* {
			padding: 0;
			margin: 0;
			outline: 0;
			box-sizing: border-box;
		}

		body {
			background-color: #8a2be2;
			color: white;
			font-family: arial;
		}

		input {
			display: block;
			height: 55px;
			width: 400px;
			margin: 10px;
			border-radius: 30px;
			border:1.2px solid white;
			font-size: 16pt;
			padding: 10px 20px;
			background-color:#8a2be2 ;
			color: white;
			outline: none;
		}

		div#corpo-form-Cad {
			width: 420px;
			margin: 80px auto;
		}

		div#corpo-form-Cad h1 {
			text-align: center;
			padding: 20px;
		}

		input[type=submit] {
			background-color: #FF0066;
			border: none;
		}

		::-webkit-input-placeholder { 
		color: #fff;
		}
    </style>
</head>
<body>
<div id="corpo-form-cad">
	<h1>Cadastrar</h1>
	<form method="POST">
		<input type="text" name="nome" placeholder="Nome Completo">
		<input type="email" name="email" placeholder="Usuário">
		<input type="password" name="senha" placeholder="Senha">
		<input type="password" name="confSenha" placeholder="Confirmar Senha">
		<input type="submit" value="Cadastrar">
	</form>
</div> 
</body>
</html>