<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $tituloPage;?></title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;500;700&display=swap');

        * {
            padding: 0;
            margin: 0;
            outline: 0;
            box-sizing: border-box;
        }

        body {
            background-color: #8a2be2;
            font-family: 'Roboto';
        }

        h1 {
            font-size: 100px;
            text-align: center;
            color: #fff;
        }
    </style>
</head>
<body>
    <h1><?php echo $titulo;?></h1>
</body>
</html>